### ISSUE TITLE
Remove unuseful line `meta: id` in info.yml

### ISSUE THREAD

**Issue by Dynnammo** [Quentinchampenois/decidim_metabase#3]
In the expression of queries, in the part : 
```
meta:
      depends_on:
        - budgets_projects
      budgets_projects: id
```
the last line is unuseful since what's needed by Metabase is always the id of the meta that the request depends on.
